FROM golang:1.22-alpine AS builder
WORKDIR /app

RUN apk add --no-cache git

ENV GONOSUMCHECK=* GOFLAGS=-mod=mod CGO_ENABLED=0

COPY scheduler/go.mod .
RUN go mod download || true

COPY scheduler/ .
RUN go mod tidy && go build -o /bin/scheduler .

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /bin/scheduler /bin/scheduler
CMD ["/bin/scheduler"]
